package com.kbap.common.domain.member.model

import com.kbap.common.domain.CurrencyCode

enum class CountryCode(val label: String, val currency: CurrencyCode) {
    AF("아프가니스탄", CurrencyCode.USD),
    AL("알바니아", CurrencyCode.USD),
    DZ("알제리", CurrencyCode.USD),
    AD("안도라", CurrencyCode.EUR),
    AO("앙골라", CurrencyCode.USD),
    AG("앤티가 바부다", CurrencyCode.USD),
    AR("아르헨티나", CurrencyCode.USD),
    AM("아르메니아", CurrencyCode.USD),
    AU("오스트레일리아", CurrencyCode.AUD),
    AT("오스트리아", CurrencyCode.EUR),
    AZ("아제르바이잔", CurrencyCode.USD),
    BS("바하마", CurrencyCode.USD),
    BH("바레인", CurrencyCode.USD),
    BD("방글라데시", CurrencyCode.USD),
    BB("바베이도스", CurrencyCode.USD),
    BY("벨라루스", CurrencyCode.USD),
    BE("벨기에", CurrencyCode.EUR),
    BZ("벨리즈", CurrencyCode.USD),
    BJ("베냉", CurrencyCode.USD),
    BT("부탄", CurrencyCode.USD),
    BO("볼리비아", CurrencyCode.USD),
    BA("보스니아 헤르체고비나", CurrencyCode.USD),
    BW("보츠와나", CurrencyCode.USD),
    BR("브라질", CurrencyCode.BRL),
    BN("브루나이", CurrencyCode.USD),
    BG("불가리아", CurrencyCode.USD),
    BF("부르키나파소", CurrencyCode.USD),
    BI("부룬디", CurrencyCode.USD),
    KH("캄보디아", CurrencyCode.USD),
    CM("카메룬", CurrencyCode.USD),
    CA("캐나다", CurrencyCode.CAD),
    CV("카보베르데", CurrencyCode.USD),
    CF("중앙 아프리카 공화국", CurrencyCode.USD),
    TD("차드", CurrencyCode.USD),
    CL("칠레", CurrencyCode.USD),
    CN("중국", CurrencyCode.CNY),
    CO("콜롬비아", CurrencyCode.USD),
    KM("코모로", CurrencyCode.USD),
    CG("콩고-브라자빌", CurrencyCode.USD),
    CD("콩고-킨샤사", CurrencyCode.USD),
    CR("코스타리카", CurrencyCode.USD),
    CI("코트디부아르", CurrencyCode.USD),
    HR("크로아티아", CurrencyCode.EUR),
    CU("쿠바", CurrencyCode.USD),
    CY("키프로스", CurrencyCode.EUR),
    CZ("체코", CurrencyCode.CZK),
    DK("덴마크", CurrencyCode.DKK),
    DJ("지부티", CurrencyCode.USD),
    DM("도미니카", CurrencyCode.USD),
    DO("도미니카 공화국", CurrencyCode.USD),
    EC("에콰도르", CurrencyCode.USD),
    EG("이집트", CurrencyCode.USD),
    SV("엘살바도르", CurrencyCode.USD),
    GQ("적도 기니", CurrencyCode.USD),
    ER("에리트리아", CurrencyCode.USD),
    EE("에스토니아", CurrencyCode.EUR),
    SZ("에스와티니", CurrencyCode.USD),
    ET("에티오피아", CurrencyCode.USD),
    FJ("피지", CurrencyCode.USD),
    FI("핀란드", CurrencyCode.EUR),
    FR("프랑스", CurrencyCode.EUR),
    GA("가봉", CurrencyCode.USD),
    GM("감비아", CurrencyCode.USD),
    GE("조지아", CurrencyCode.USD),
    DE("독일", CurrencyCode.EUR),
    GH("가나", CurrencyCode.USD),
    GR("그리스", CurrencyCode.EUR),
    GD("그레나다", CurrencyCode.USD),
    GT("과테말라", CurrencyCode.USD),
    GN("기니", CurrencyCode.USD),
    GW("기니비사우", CurrencyCode.USD),
    GY("가이아나", CurrencyCode.USD),
    HT("아이티", CurrencyCode.USD),
    HN("온두라스", CurrencyCode.USD),
    HK("홍콩", CurrencyCode.HKD),
    HU("헝가리", CurrencyCode.HUF),
    IS("아이슬란드", CurrencyCode.ISK),
    IN("인도", CurrencyCode.INR),
    ID("인도네시아", CurrencyCode.IDR),
    IR("이란", CurrencyCode.USD),
    IQ("이라크", CurrencyCode.USD),
    IE("아일랜드", CurrencyCode.EUR),
    IL("이스라엘", CurrencyCode.ILS),
    IT("이탈리아", CurrencyCode.EUR),
    JM("자메이카", CurrencyCode.USD),
    JP("일본", CurrencyCode.JPY),
    JO("요르단", CurrencyCode.USD),
    KZ("카자흐스탄", CurrencyCode.USD),
    KE("케냐", CurrencyCode.USD),
    KI("키리바시", CurrencyCode.AUD),
    KW("쿠웨이트", CurrencyCode.USD),
    KG("키르기스스탄", CurrencyCode.USD),
    LA("라오스", CurrencyCode.USD),
    LV("라트비아", CurrencyCode.EUR),
    LB("레바논", CurrencyCode.USD),
    LS("레소토", CurrencyCode.USD),
    LR("라이베리아", CurrencyCode.USD),
    LY("리비아", CurrencyCode.USD),
    LI("리히텐슈타인", CurrencyCode.CHF),
    LT("리투아니아", CurrencyCode.EUR),
    LU("룩셈부르크", CurrencyCode.EUR),
    MO("마카오", CurrencyCode.USD),
    MG("마다가스카르", CurrencyCode.USD),
    MW("말라위", CurrencyCode.USD),
    MY("말레이시아", CurrencyCode.MYR),
    MV("몰디브", CurrencyCode.USD),
    ML("말리", CurrencyCode.USD),
    MT("몰타", CurrencyCode.EUR),
    MH("마셜 제도", CurrencyCode.USD),
    MR("모리타니", CurrencyCode.USD),
    MU("모리셔스", CurrencyCode.USD),
    MX("멕시코", CurrencyCode.MXN),
    FM("미크로네시아", CurrencyCode.USD),
    MD("몰도바", CurrencyCode.USD),
    MC("모나코", CurrencyCode.EUR),
    MN("몽골", CurrencyCode.USD),
    ME("몬테네그로", CurrencyCode.EUR),
    MA("모로코", CurrencyCode.USD),
    MZ("모잠비크", CurrencyCode.USD),
    MM("미얀마", CurrencyCode.USD),
    NA("나미비아", CurrencyCode.USD),
    NR("나우루", CurrencyCode.AUD),
    NP("네팔", CurrencyCode.USD),
    NL("네덜란드", CurrencyCode.EUR),
    NZ("뉴질랜드", CurrencyCode.NZD),
    NI("니카라과", CurrencyCode.USD),
    NE("니제르", CurrencyCode.USD),
    NG("나이지리아", CurrencyCode.USD),
    KP("북한", CurrencyCode.USD),
    MK("북마케도니아", CurrencyCode.USD),
    NO("노르웨이", CurrencyCode.NOK),
    OM("오만", CurrencyCode.USD),
    PK("파키스탄", CurrencyCode.USD),
    PW("팔라우", CurrencyCode.USD),
    PS("팔레스타인 지구", CurrencyCode.ILS),
    PA("파나마", CurrencyCode.USD),
    PG("파푸아뉴기니", CurrencyCode.USD),
    PY("파라과이", CurrencyCode.USD),
    PE("페루", CurrencyCode.USD),
    PH("필리핀", CurrencyCode.PHP),
    PL("폴란드", CurrencyCode.PLN),
    PT("포르투갈", CurrencyCode.EUR),
    QA("카타르", CurrencyCode.USD),
    RO("루마니아", CurrencyCode.RON),
    RU("러시아", CurrencyCode.USD),
    RW("르완다", CurrencyCode.USD),
    KN("세인트키츠 네비스", CurrencyCode.USD),
    LC("세인트루시아", CurrencyCode.USD),
    VC("세인트빈센트그레나딘", CurrencyCode.USD),
    WS("사모아", CurrencyCode.USD),
    SM("산마리노", CurrencyCode.EUR),
    ST("상투메 프린시페", CurrencyCode.USD),
    SA("사우디아라비아", CurrencyCode.USD),
    SN("세네갈", CurrencyCode.USD),
    RS("세르비아", CurrencyCode.USD),
    SC("세이셸", CurrencyCode.USD),
    SL("시에라리온", CurrencyCode.USD),
    SG("싱가포르", CurrencyCode.SGD),
    SK("슬로바키아", CurrencyCode.EUR),
    SI("슬로베니아", CurrencyCode.EUR),
    SB("솔로몬 제도", CurrencyCode.USD),
    SO("소말리아", CurrencyCode.USD),
    ZA("남아프리카", CurrencyCode.ZAR),
    KR("대한민국", CurrencyCode.KRW),
    SS("남수단", CurrencyCode.USD),
    ES("스페인", CurrencyCode.EUR),
    LK("스리랑카", CurrencyCode.USD),
    SD("수단", CurrencyCode.USD),
    SR("수리남", CurrencyCode.USD),
    SE("스웨덴", CurrencyCode.SEK),
    CH("스위스", CurrencyCode.CHF),
    SY("시리아", CurrencyCode.USD),
    TW("대만", CurrencyCode.USD),
    TJ("타지키스탄", CurrencyCode.USD),
    TZ("탄자니아", CurrencyCode.USD),
    TH("태국", CurrencyCode.THB),
    TL("동티모르", CurrencyCode.USD),
    TG("토고", CurrencyCode.USD),
    TO("통가", CurrencyCode.USD),
    TT("트리니다드 토바고", CurrencyCode.USD),
    TN("튀니지", CurrencyCode.USD),
    TR("튀르키예", CurrencyCode.TRY),
    TM("투르크메니스탄", CurrencyCode.USD),
    TV("투발루", CurrencyCode.AUD),
    UG("우간다", CurrencyCode.USD),
    UA("우크라이나", CurrencyCode.USD),
    AE("아랍에미리트", CurrencyCode.USD),
    GB("영국", CurrencyCode.GBP),
    US("미국", CurrencyCode.USD),
    UY("우루과이", CurrencyCode.USD),
    UZ("우즈베키스탄", CurrencyCode.USD),
    VU("바누아투", CurrencyCode.USD),
    VE("베네수엘라", CurrencyCode.USD),
    VN("베트남", CurrencyCode.USD),
    YE("예멘", CurrencyCode.USD),
    ZM("잠비아", CurrencyCode.USD),
    ZW("짐바브웨", CurrencyCode.USD),
    ;

    companion object {
        fun from(code: String?): CountryCode? = entries.firstOrNull { it.name == code }
    }
}
