services:
  jenkins:
    build: .
    container_name: kbap-jenkins
    ports:
      - "8080:8080"
    volumes:
      - jenkins-home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins-home: {}
