package com.kbap.api.ingredient

import com.kbap.common.domain.ingredient.model.IngredientCode
import com.kbap.common.domain.ingredient.model.IngredientCode.*

enum class DietCategory(
    val koreanName: String,
    val avoidedIngredients: Set<IngredientCode>,
) {
    VEGAN(
        "비건",
        setOf(
            EGG, MILK, DAIRY, GOAT_MILK, BUTTER, GHEE, CHEESE, GELATIN, RENNET, HONEY, CARMINE,
            SHRIMP, SALTED_SHRIMP, CRAB, CRAYFISH, LOBSTER, SQUID, OCTOPUS, OYSTER, OYSTER_SAUCE,
            ABALONE, MUSSEL, CLAM, SHORT_NECK_CLAM, SCALLOP, SEAFOOD, FISH, MACKEREL, SALMON, TUNA,
            COD, ANCHOVY, FISH_SAUCE, BROTH, DASHI, BEEF, PORK, LARD, TALLOW, CHICKEN, POULTRY,
        ),
    ),
    VEGETARIAN(
        "베지테리언",
        setOf(
            GELATIN, RENNET, CARMINE,
            SHRIMP, SALTED_SHRIMP, CRAB, CRAYFISH, LOBSTER, SQUID, OCTOPUS, OYSTER, OYSTER_SAUCE,
            ABALONE, MUSSEL, CLAM, SHORT_NECK_CLAM, SCALLOP, SEAFOOD, FISH, MACKEREL, SALMON, TUNA,
            COD, ANCHOVY, FISH_SAUCE, BROTH, DASHI, BEEF, PORK, LARD, TALLOW, CHICKEN, POULTRY,
        ),
    ),
    LACTO_VEGETARIAN(
        "락토 베지테리언",
        setOf(
            EGG, GELATIN, RENNET, CARMINE,
            SHRIMP, SALTED_SHRIMP, CRAB, CRAYFISH, LOBSTER, SQUID, OCTOPUS, OYSTER, OYSTER_SAUCE,
            ABALONE, MUSSEL, CLAM, SHORT_NECK_CLAM, SCALLOP, SEAFOOD, FISH, MACKEREL, SALMON, TUNA,
            COD, ANCHOVY, FISH_SAUCE, BROTH, DASHI, BEEF, PORK, LARD, TALLOW, CHICKEN, POULTRY,
        ),
    ),
    OVO_VEGETARIAN(
        "오보 베지테리언",
        setOf(
            MILK, DAIRY, GOAT_MILK, BUTTER, GHEE, CHEESE, GELATIN, RENNET, CARMINE,
            SHRIMP, SALTED_SHRIMP, CRAB, CRAYFISH, LOBSTER, SQUID, OCTOPUS, OYSTER, OYSTER_SAUCE,
            ABALONE, MUSSEL, CLAM, SHORT_NECK_CLAM, SCALLOP, SEAFOOD, FISH, MACKEREL, SALMON, TUNA,
            COD, ANCHOVY, FISH_SAUCE, BROTH, DASHI, BEEF, PORK, LARD, TALLOW, CHICKEN, POULTRY,
        ),
    ),
    PESCATARIAN(
        "페스코테리언",
        setOf(GELATIN, RENNET, CARMINE, BROTH, BEEF, PORK, LARD, TALLOW, CHICKEN, POULTRY),
    ),
    GLUTEN_FREE(
        "글루텐 프리",
        setOf(WHEAT, BARLEY, RYE, OAT),
    ),
    LACTOSE_FREE(
        "유당 불내증",
        setOf(MILK, DAIRY, GOAT_MILK, BUTTER, GHEE, CHEESE),
    ),
    NO_ALCOHOL(
        "무알코올",
        setOf(ALCOHOL, MIRIN, COOKING_WINE),
    ),
    MUSLIM(
        "무슬림(할랄)",
        setOf(GELATIN, RENNET, CARMINE, BROTH, PORK, LARD, TALLOW, ALCOHOL, MIRIN, COOKING_WINE),
    ),
    HINDU(
        "힌두교",
        setOf(GELATIN, RENNET, BROTH, BEEF, TALLOW),
    ),
    KOSHER(
        "유대교(코셔)",
        setOf(
            GELATIN, RENNET, CARMINE,
            SHRIMP, SALTED_SHRIMP, CRAB, CRAYFISH, LOBSTER, SQUID, OCTOPUS, OYSTER, OYSTER_SAUCE,
            ABALONE, MUSSEL, CLAM, SHORT_NECK_CLAM, SCALLOP, SEAFOOD,
            BROTH, PORK, LARD,
        ),
    ),
    BUDDHIST(
        "불교(사찰식)",
        setOf(
            EGG, GELATIN, RENNET, CARMINE,
            SHRIMP, SALTED_SHRIMP, CRAB, CRAYFISH, LOBSTER, SQUID, OCTOPUS, OYSTER, OYSTER_SAUCE,
            ABALONE, MUSSEL, CLAM, SHORT_NECK_CLAM, SCALLOP, SEAFOOD, FISH, MACKEREL, SALMON, TUNA,
            COD, ANCHOVY, FISH_SAUCE, BROTH, DASHI, BEEF, PORK, LARD, TALLOW, CHICKEN, POULTRY,
            ONION, GARLIC, SCALLION, CHIVE, WILD_CHIVE, ASAFOETIDA,
        ),
    ),
    JAIN(
        "자이나교",
        setOf(
            EGG, GELATIN, RENNET, HONEY, CARMINE,
            SHRIMP, SALTED_SHRIMP, CRAB, CRAYFISH, LOBSTER, SQUID, OCTOPUS, OYSTER, OYSTER_SAUCE,
            ABALONE, MUSSEL, CLAM, SHORT_NECK_CLAM, SCALLOP, SEAFOOD, FISH, MACKEREL, SALMON, TUNA,
            COD, ANCHOVY, FISH_SAUCE, BROTH, DASHI, BEEF, PORK, LARD, TALLOW, CHICKEN, POULTRY,
            POTATO, CARROT, ONION, GARLIC, SCALLION, CHIVE, WILD_CHIVE,
        ),
    ),
    NUT_ALLERGY(
        "견과류 알레르기",
        setOf(WALNUT, PINE_NUT, ALMOND, CASHEW, PISTACHIO, HAZELNUT, MACADAMIA, PECAN, BRAZIL_NUT, CHESTNUT),
    ),
    SHELLFISH_ALLERGY(
        "갑각류·조개 알레르기",
        setOf(
            SHRIMP, SALTED_SHRIMP, CRAB, CRAYFISH, LOBSTER, SQUID, OCTOPUS, OYSTER, OYSTER_SAUCE,
            ABALONE, MUSSEL, CLAM, SHORT_NECK_CLAM, SCALLOP, SEAFOOD,
        ),
    ),
}
