-- KB-163: 기피물질 카탈로그 마스터 시드 81종 — 전 환경 공통 (AvoidanceSubstanceCode enum 과 시드-동기화 테스트로 정합 강제)

INSERT INTO avoidance_substance (code, korean_name, translations) VALUES
('EGG', '계란', '{"en": "Egg", "es": "Huevo", "id": "Telur", "ja": "卵", "ru": "Яйцо", "th": "ไข่", "vi": "Trứng", "zh-Hans": "鸡蛋", "zh-Hant": "雞蛋"}'),
('MILK', '우유', '{"en": "Milk", "es": "Leche", "id": "Susu", "ja": "牛乳", "ru": "Молоко", "th": "นม", "vi": "Sữa", "zh-Hans": "牛奶", "zh-Hant": "牛奶"}'),
('DAIRY', '유제품', '{"en": "Dairy products", "es": "Productos lácteos", "id": "Produk susu", "ja": "乳製品", "ru": "Молочные продукты", "th": "ผลิตภัณฑ์จากนม", "vi": "Sản phẩm từ sữa", "zh-Hans": "乳制品", "zh-Hant": "乳製品"}'),
('GOAT_MILK', '산양유', '{"en": "Goat milk", "es": "Leche de cabra", "id": "Susu kambing", "ja": "山羊乳", "ru": "Козье молоко", "th": "นมแพะ", "vi": "Sữa dê", "zh-Hans": "山羊奶", "zh-Hant": "山羊奶"}'),
('BUTTER', '버터', '{"en": "Butter", "es": "Mantequilla", "id": "Mentega", "ja": "バター", "ru": "Сливочное масло", "th": "เนย", "vi": "Bơ", "zh-Hans": "黄油", "zh-Hant": "奶油"}'),
('GHEE', '기버터', '{"en": "Ghee", "es": "Ghee", "id": "Ghee", "ja": "ギー", "ru": "Гхи", "th": "กี", "vi": "Bơ ghee", "zh-Hans": "酥油", "zh-Hant": "酥油"}'),
('CHEESE', '치즈', '{"en": "Cheese", "es": "Queso", "id": "Keju", "ja": "チーズ", "ru": "Сыр", "th": "ชีส", "vi": "Phô mai", "zh-Hans": "奶酪", "zh-Hant": "起司"}'),
('GELATIN', '젤라틴', '{"en": "Gelatin", "es": "Gelatina", "id": "Gelatin", "ja": "ゼラチン", "ru": "Желатин", "th": "เจลาติน", "vi": "Gelatin", "zh-Hans": "明胶", "zh-Hant": "明膠"}'),
('RENNET', '레닛', '{"en": "Rennet", "es": "Cuajo", "id": "Rennet", "ja": "レンネット", "ru": "Сычужный фермент", "th": "เรนเนต", "vi": "Men dịch vị", "zh-Hans": "凝乳酶", "zh-Hant": "凝乳酶"}'),
('HONEY', '꿀', '{"en": "Honey", "es": "Miel", "id": "Madu", "ja": "はちみつ", "ru": "Мёд", "th": "น้ำผึ้ง", "vi": "Mật ong", "zh-Hans": "蜂蜜", "zh-Hant": "蜂蜜"}'),
('CARMINE', '카민', '{"en": "Carmine", "es": "Carmín", "id": "Karmin", "ja": "カルミン", "ru": "Кармин", "th": "คาร์มีน", "vi": "Carmine", "zh-Hans": "胭脂红", "zh-Hant": "胭脂紅"}'),
('PEANUT', '땅콩', '{"en": "Peanut", "es": "Cacahuete", "id": "Kacang tanah", "ja": "ピーナッツ", "ru": "Арахис", "th": "ถั่วลิสง", "vi": "Đậu phộng", "zh-Hans": "花生", "zh-Hant": "花生"}'),
('WALNUT', '호두', '{"en": "Walnut", "es": "Nuez", "id": "Kenari", "ja": "くるみ", "ru": "Грецкий орех", "th": "วอลนัท", "vi": "Óc chó", "zh-Hans": "核桃", "zh-Hant": "核桃"}'),
('PINE_NUT', '잣', '{"en": "Pine nut", "es": "Piñón", "id": "Kacang pinus", "ja": "松の実", "ru": "Кедровый орех", "th": "เมล็ดสน", "vi": "Hạt thông", "zh-Hans": "松子", "zh-Hant": "松子"}'),
('ALMOND', '아몬드', '{"en": "Almond", "es": "Almendra", "id": "Almond", "ja": "アーモンド", "ru": "Миндаль", "th": "อัลมอนด์", "vi": "Hạnh nhân", "zh-Hans": "杏仁", "zh-Hant": "杏仁"}'),
('CASHEW', '캐슈넛', '{"en": "Cashew nut", "es": "Anacardo", "id": "Kacang mete", "ja": "カシューナッツ", "ru": "Кешью", "th": "เม็ดมะม่วงหิมพานต์", "vi": "Hạt điều", "zh-Hans": "腰果", "zh-Hant": "腰果"}'),
('PISTACHIO', '피스타치오', '{"en": "Pistachio", "es": "Pistacho", "id": "Pistachio", "ja": "ピスタチオ", "ru": "Фисташка", "th": "พิสตาชิโอ", "vi": "Hạt dẻ cười", "zh-Hans": "开心果", "zh-Hant": "開心果"}'),
('HAZELNUT', '헤이즐넛', '{"en": "Hazelnut", "es": "Avellana", "id": "Hazelnut", "ja": "ヘーゼルナッツ", "ru": "Фундук", "th": "เฮเซลนัท", "vi": "Hạt phỉ", "zh-Hans": "榛子", "zh-Hant": "榛果"}'),
('MACADAMIA', '마카다미아', '{"en": "Macadamia nut", "es": "Macadamia", "id": "Kacang macadamia", "ja": "マカダミアナッツ", "ru": "Макадамия", "th": "แมคคาเดเมีย", "vi": "Hạt mắc ca", "zh-Hans": "夏威夷果", "zh-Hant": "夏威夷豆"}'),
('PECAN', '피칸', '{"en": "Pecan", "es": "Pacana", "id": "Pecan", "ja": "ピーカンナッツ", "ru": "Пекан", "th": "พีแคน", "vi": "Hạt hồ đào", "zh-Hans": "碧根果", "zh-Hant": "碧根果"}'),
('BRAZIL_NUT', '브라질너트', '{"en": "Brazil nut", "es": "Nuez de Brasil", "id": "Kacang Brazil", "ja": "ブラジルナッツ", "ru": "Бразильский орех", "th": "บราซิลนัท", "vi": "Hạt Brazil", "zh-Hans": "巴西坚果", "zh-Hant": "巴西堅果"}'),
('CHESTNUT', '밤', '{"en": "Chestnut", "es": "Castaña", "id": "Kastanya", "ja": "栗", "ru": "Каштан", "th": "เกาลัด", "vi": "Hạt dẻ", "zh-Hans": "栗子", "zh-Hant": "栗子"}'),
('SESAME', '참깨', '{"en": "Sesame", "es": "Sésamo", "id": "Wijen", "ja": "ごま", "ru": "Кунжут", "th": "งา", "vi": "Vừng", "zh-Hans": "芝麻", "zh-Hant": "芝麻"}'),
('SUNFLOWER_SEED', '해바라기씨', '{"en": "Sunflower seed", "es": "Semilla de girasol", "id": "Biji bunga matahari", "ja": "ひまわりの種", "ru": "Семена подсолнечника", "th": "เมล็ดทานตะวัน", "vi": "Hạt hướng dương", "zh-Hans": "葵花籽", "zh-Hant": "葵花籽"}'),
('MUSTARD', '겨자', '{"en": "Mustard", "es": "Mostaza", "id": "Moster", "ja": "からし", "ru": "Горчица", "th": "มัสตาร์ด", "vi": "Mù tạt", "zh-Hans": "芥末", "zh-Hant": "芥末"}'),
('WHEAT', '밀', '{"en": "Wheat", "es": "Trigo", "id": "Gandum", "ja": "小麦", "ru": "Пшеница", "th": "ข้าวสาลี", "vi": "Lúa mì", "zh-Hans": "小麦", "zh-Hant": "小麥"}'),
('BUCKWHEAT', '메밀', '{"en": "Buckwheat", "es": "Trigo sarraceno", "id": "Soba", "ja": "そば", "ru": "Гречка", "th": "บัควีท", "vi": "Kiều mạch", "zh-Hans": "荞麦", "zh-Hant": "蕎麥"}'),
('BARLEY', '보리', '{"en": "Barley", "es": "Cebada", "id": "Jelai", "ja": "大麦", "ru": "Ячмень", "th": "ข้าวบาร์เลย์", "vi": "Lúa mạch", "zh-Hans": "大麦", "zh-Hant": "大麥"}'),
('RYE', '호밀', '{"en": "Rye", "es": "Centeno", "id": "Rye", "ja": "ライ麦", "ru": "Рожь", "th": "ไรย์", "vi": "Lúa mạch đen", "zh-Hans": "黑麦", "zh-Hant": "黑麥"}'),
('OAT', '귀리', '{"en": "Oat", "es": "Avena", "id": "Oat", "ja": "オーツ麦", "ru": "Овёс", "th": "ข้าวโอ๊ต", "vi": "Yến mạch", "zh-Hans": "燕麦", "zh-Hant": "燕麥"}'),
('CORN', '옥수수', '{"en": "Corn", "es": "Maíz", "id": "Jagung", "ja": "とうもろこし", "ru": "Кукуруза", "th": "ข้าวโพด", "vi": "Ngô", "zh-Hans": "玉米", "zh-Hant": "玉米"}'),
('SOY', '대두', '{"en": "Soybean", "es": "Soja", "id": "Kedelai", "ja": "大豆", "ru": "Соя", "th": "ถั่วเหลือง", "vi": "Đậu nành", "zh-Hans": "大豆", "zh-Hant": "大豆"}'),
('LUPIN', '루핀', '{"en": "Lupin", "es": "Altramuz", "id": "Lupin", "ja": "ルピナス", "ru": "Люпин", "th": "ลูปิน", "vi": "Đậu lupin", "zh-Hans": "羽扇豆", "zh-Hant": "羽扇豆"}'),
('PEA', '완두콩', '{"en": "Pea", "es": "Guisante", "id": "Kacang polong", "ja": "えんどう豆", "ru": "Горох", "th": "ถั่วลันเตา", "vi": "Đậu Hà Lan", "zh-Hans": "豌豆", "zh-Hant": "豌豆"}'),
('CHICKPEA', '병아리콩', '{"en": "Chickpea", "es": "Garbanzo", "id": "Kacang arab", "ja": "ひよこ豆", "ru": "Нут", "th": "ถั่วลูกไก่", "vi": "Đậu gà", "zh-Hans": "鹰嘴豆", "zh-Hant": "鷹嘴豆"}'),
('LENTIL', '렌틸콩', '{"en": "Lentil", "es": "Lenteja", "id": "Lentil", "ja": "レンズ豆", "ru": "Чечевица", "th": "ถั่วเลนทิล", "vi": "Đậu lăng", "zh-Hans": "扁豆", "zh-Hant": "扁豆"}'),
('SHRIMP', '새우', '{"en": "Shrimp", "es": "Camarón", "id": "Udang", "ja": "エビ", "ru": "Креветка", "th": "กุ้ง", "vi": "Tôm", "zh-Hans": "虾", "zh-Hant": "蝦"}'),
('SALTED_SHRIMP', '새우젓', '{"en": "Salted shrimp", "es": "Camarón salado fermentado", "id": "Udang asin fermentasi", "ja": "アミの塩辛", "ru": "Солёные креветки", "th": "กุ้งเค็มหมัก", "vi": "Tôm muối", "zh-Hans": "盐渍虾", "zh-Hant": "鹽漬蝦"}'),
('CRAB', '게', '{"en": "Crab", "es": "Cangrejo", "id": "Kepiting", "ja": "カニ", "ru": "Краб", "th": "ปู", "vi": "Cua", "zh-Hans": "蟹", "zh-Hant": "蟹"}'),
('CRAYFISH', '가재', '{"en": "Crayfish", "es": "Cangrejo de río", "id": "Lobster air tawar", "ja": "ザリガニ", "ru": "Речной рак", "th": "เครย์ฟิช", "vi": "Tôm càng", "zh-Hans": "小龙虾", "zh-Hant": "小龍蝦"}'),
('LOBSTER', '랍스터', '{"en": "Lobster", "es": "Langosta", "id": "Lobster", "ja": "ロブスター", "ru": "Омар", "th": "ล็อบสเตอร์", "vi": "Tôm hùm", "zh-Hans": "龙虾", "zh-Hant": "龍蝦"}'),
('SQUID', '오징어', '{"en": "Squid", "es": "Calamar", "id": "Cumi-cumi", "ja": "イカ", "ru": "Кальмар", "th": "ปลาหมึก", "vi": "Mực", "zh-Hans": "鱿鱼", "zh-Hant": "魷魚"}'),
('OCTOPUS', '문어', '{"en": "Octopus", "es": "Pulpo", "id": "Gurita", "ja": "タコ", "ru": "Осьминог", "th": "หมึกยักษ์", "vi": "Bạch tuộc", "zh-Hans": "章鱼", "zh-Hant": "章魚"}'),
('OYSTER', '굴', '{"en": "Oyster", "es": "Ostra", "id": "Tiram", "ja": "牡蠣", "ru": "Устрица", "th": "หอยนางรม", "vi": "Hàu", "zh-Hans": "牡蛎", "zh-Hant": "牡蠣"}'),
('OYSTER_SAUCE', '굴소스', '{"en": "Oyster sauce", "es": "Salsa de ostras", "id": "Saus tiram", "ja": "オイスターソース", "ru": "Устричный соус", "th": "ซอสหอยนางรม", "vi": "Dầu hào", "zh-Hans": "蚝油", "zh-Hant": "蠔油"}'),
('ABALONE', '전복', '{"en": "Abalone", "es": "Abulón", "id": "Abalon", "ja": "アワビ", "ru": "Морское ушко", "th": "หอยเป๋าฮื้อ", "vi": "Bào ngư", "zh-Hans": "鲍鱼", "zh-Hant": "鮑魚"}'),
('MUSSEL', '홍합', '{"en": "Mussel", "es": "Mejillón", "id": "Kerang hijau", "ja": "ムール貝", "ru": "Мидия", "th": "หอยแมลงภู่", "vi": "Vẹm", "zh-Hans": "贻贝", "zh-Hant": "貽貝"}'),
('CLAM', '조개', '{"en": "Clam", "es": "Almeja", "id": "Kerang", "ja": "貝", "ru": "Моллюск", "th": "หอย", "vi": "Nghêu", "zh-Hans": "蛤蜊", "zh-Hant": "蛤蜊"}'),
('SHORT_NECK_CLAM', '바지락', '{"en": "Short-neck clam", "es": "Almeja japonesa", "id": "Kerang asari", "ja": "アサリ", "ru": "Маленькая венерка", "th": "หอยลาย", "vi": "Nghêu cổ ngắn", "zh-Hans": "菲律宾蛤仔", "zh-Hant": "菲律賓蛤仔"}'),
('SCALLOP', '가리비', '{"en": "Scallop", "es": "Vieira", "id": "Kerang simping", "ja": "ホタテ", "ru": "Морской гребешок", "th": "หอยเชลล์", "vi": "Sò điệp", "zh-Hans": "扇贝", "zh-Hant": "扇貝"}'),
('SEAFOOD', '해산물', '{"en": "Seafood", "es": "Mariscos", "id": "Makanan laut", "ja": "海産物", "ru": "Морепродукты", "th": "อาหารทะเล", "vi": "Hải sản", "zh-Hans": "海鲜", "zh-Hant": "海鮮"}'),
('FISH', '생선', '{"en": "Fish", "es": "Pescado", "id": "Ikan", "ja": "魚", "ru": "Рыба", "th": "ปลา", "vi": "Cá", "zh-Hans": "鱼", "zh-Hant": "魚"}'),
('MACKEREL', '고등어', '{"en": "Mackerel", "es": "Caballa", "id": "Ikan kembung", "ja": "サバ", "ru": "Скумбрия", "th": "ปลาแมกเคอเรล", "vi": "Cá thu", "zh-Hans": "鲭鱼", "zh-Hant": "鯖魚"}'),
('SALMON', '연어', '{"en": "Salmon", "es": "Salmón", "id": "Salmon", "ja": "サーモン", "ru": "Лосось", "th": "ปลาแซลมอน", "vi": "Cá hồi", "zh-Hans": "三文鱼", "zh-Hant": "鮭魚"}'),
('TUNA', '참치', '{"en": "Tuna", "es": "Atún", "id": "Tuna", "ja": "マグロ", "ru": "Тунец", "th": "ปลาทูน่า", "vi": "Cá ngừ", "zh-Hans": "金枪鱼", "zh-Hant": "鮪魚"}'),
('COD', '대구', '{"en": "Cod", "es": "Bacalao", "id": "Ikan kod", "ja": "タラ", "ru": "Треска", "th": "ปลาค็อด", "vi": "Cá tuyết", "zh-Hans": "鳕鱼", "zh-Hant": "鱈魚"}'),
('ANCHOVY', '멸치', '{"en": "Anchovy", "es": "Anchoa", "id": "Ikan teri", "ja": "カタクチイワシ", "ru": "Анчоус", "th": "ปลาแอนโชวี่", "vi": "Cá cơm", "zh-Hans": "凤尾鱼", "zh-Hant": "鳳尾魚"}'),
('FISH_SAUCE', '액젓', '{"en": "Fish sauce", "es": "Salsa de pescado", "id": "Kecap ikan", "ja": "魚醤", "ru": "Рыбный соус", "th": "น้ำปลา", "vi": "Nước mắm", "zh-Hans": "鱼露", "zh-Hant": "魚露"}'),
('BROTH', '육수', '{"en": "Broth", "es": "Caldo", "id": "Kaldu", "ja": "だし汁", "ru": "Бульон", "th": "น้ำซุป", "vi": "Nước dùng", "zh-Hans": "高汤", "zh-Hant": "高湯"}'),
('DASHI', '다시', '{"en": "Dashi", "es": "Dashi", "id": "Dashi", "ja": "出汁", "ru": "Даси", "th": "ดาชิ", "vi": "Nước dùng dashi", "zh-Hans": "日式高汤", "zh-Hant": "日式高湯"}'),
('BEEF', '소고기', '{"en": "Beef", "es": "Carne de res", "id": "Daging sapi", "ja": "牛肉", "ru": "Говядина", "th": "เนื้อวัว", "vi": "Thịt bò", "zh-Hans": "牛肉", "zh-Hant": "牛肉"}'),
('PORK', '돼지고기', '{"en": "Pork", "es": "Carne de cerdo", "id": "Daging babi", "ja": "豚肉", "ru": "Свинина", "th": "เนื้อหมู", "vi": "Thịt heo", "zh-Hans": "猪肉", "zh-Hant": "豬肉"}'),
('LARD', '라드', '{"en": "Lard", "es": "Manteca de cerdo", "id": "Lemak babi", "ja": "ラード", "ru": "Смалец", "th": "น้ำมันหมู", "vi": "Mỡ heo", "zh-Hans": "猪油", "zh-Hant": "豬油"}'),
('TALLOW', '우지', '{"en": "Tallow", "es": "Sebo", "id": "Lemak sapi", "ja": "牛脂", "ru": "Говяжий жир", "th": "ไขมันวัว", "vi": "Mỡ bò", "zh-Hans": "牛脂", "zh-Hant": "牛脂"}'),
('CHICKEN', '닭고기', '{"en": "Chicken", "es": "Pollo", "id": "Daging ayam", "ja": "鶏肉", "ru": "Курица", "th": "เนื้อไก่", "vi": "Thịt gà", "zh-Hans": "鸡肉", "zh-Hant": "雞肉"}'),
('POULTRY', '가금류', '{"en": "Poultry", "es": "Aves de corral", "id": "Unggas", "ja": "家禽類", "ru": "Птица", "th": "สัตว์ปีก", "vi": "Gia cầm", "zh-Hans": "家禽", "zh-Hant": "家禽"}'),
('PEACH', '복숭아', '{"en": "Peach", "es": "Melocotón", "id": "Persik", "ja": "桃", "ru": "Персик", "th": "ลูกพีช", "vi": "Đào", "zh-Hans": "桃子", "zh-Hant": "桃子"}'),
('TOMATO', '토마토', '{"en": "Tomato", "es": "Tomate", "id": "Tomat", "ja": "トマト", "ru": "Помидор", "th": "มะเขือเทศ", "vi": "Cà chua", "zh-Hans": "番茄", "zh-Hant": "番茄"}'),
('CELERY', '셀러리', '{"en": "Celery", "es": "Apio", "id": "Seledri", "ja": "セロリ", "ru": "Сельдерей", "th": "ขึ้นฉ่าย", "vi": "Cần tây", "zh-Hans": "芹菜", "zh-Hant": "芹菜"}'),
('POTATO', '감자', '{"en": "Potato", "es": "Patata", "id": "Kentang", "ja": "じゃがいも", "ru": "Картофель", "th": "มันฝรั่ง", "vi": "Khoai tây", "zh-Hans": "土豆", "zh-Hant": "馬鈴薯"}'),
('CARROT', '당근', '{"en": "Carrot", "es": "Zanahoria", "id": "Wortel", "ja": "にんじん", "ru": "Морковь", "th": "แครอท", "vi": "Cà rốt", "zh-Hans": "胡萝卜", "zh-Hant": "胡蘿蔔"}'),
('ONION', '양파', '{"en": "Onion", "es": "Cebolla", "id": "Bawang bombai", "ja": "玉ねぎ", "ru": "Лук", "th": "หัวหอม", "vi": "Hành tây", "zh-Hans": "洋葱", "zh-Hant": "洋蔥"}'),
('GARLIC', '마늘', '{"en": "Garlic", "es": "Ajo", "id": "Bawang putih", "ja": "にんにく", "ru": "Чеснок", "th": "กระเทียม", "vi": "Tỏi", "zh-Hans": "大蒜", "zh-Hant": "大蒜"}'),
('SCALLION', '파', '{"en": "Scallion", "es": "Cebolleta", "id": "Daun bawang", "ja": "長ねぎ", "ru": "Зелёный лук", "th": "ต้นหอม", "vi": "Hành lá", "zh-Hans": "大葱", "zh-Hant": "青蔥"}'),
('CHIVE', '부추', '{"en": "Chive", "es": "Cebollino", "id": "Kucai", "ja": "ニラ", "ru": "Шнитт-лук", "th": "กุยช่าย", "vi": "Hẹ", "zh-Hans": "韭菜", "zh-Hant": "韭菜"}'),
('WILD_CHIVE', '달래', '{"en": "Wild chive", "es": "Cebollino silvestre", "id": "Kucai liar", "ja": "ヒメニラ", "ru": "Дикий шнитт-лук", "th": "กุยช่ายป่า", "vi": "Hẹ dại", "zh-Hans": "野葱", "zh-Hant": "野蔥"}'),
('ASAFOETIDA', '흥거', '{"en": "Asafoetida", "es": "Asafétida", "id": "Asafetida", "ja": "アサフェティダ", "ru": "Асафетида", "th": "มหาหิงคุ์", "vi": "A nguỳ", "zh-Hans": "阿魏", "zh-Hant": "阿魏"}'),
('ALCOHOL', '알코올', '{"en": "Alcohol", "es": "Alcohol", "id": "Alkohol", "ja": "アルコール", "ru": "Алкоголь", "th": "แอลกอฮอล์", "vi": "Cồn", "zh-Hans": "酒精", "zh-Hant": "酒精"}'),
('MIRIN', '미림', '{"en": "Mirin", "es": "Mirin", "id": "Mirin", "ja": "みりん", "ru": "Мирин", "th": "มิริน", "vi": "Rượu mirin", "zh-Hans": "味醂", "zh-Hant": "味醂"}'),
('COOKING_WINE', '맛술', '{"en": "Cooking wine", "es": "Vino de cocina", "id": "Anggur masak", "ja": "料理酒", "ru": "Кулинарное вино", "th": "ไวน์ปรุงอาหาร", "vi": "Rượu nấu ăn", "zh-Hans": "料酒", "zh-Hant": "料理酒"}'),
('SULFITES', '아황산류', '{"en": "Sulfites", "es": "Sulfitos", "id": "Sulfit", "ja": "亜硫酸塩", "ru": "Сульфиты", "th": "ซัลไฟต์", "vi": "Sulfite", "zh-Hans": "亚硫酸盐", "zh-Hant": "亞硫酸鹽"}');
