name: Build with Gradle

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

jobs:
  build:
    name: gradle build and test
    runs-on: ubuntu-latest

    steps:
      # 1. 소스 체크아웃
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build
